version: 0.2
phases:
  build:
    commands:
      - echo Parsing test reports
reports:
  php-report:
    files:
      - "reports/php-unit.xml"
    file-format: "JUNITXML"
  nunit-report:
    files:
      - "reports/test-nunit.xml"
    file-format: "NUNITXML"
