version: 0.2
phases:
  build:
    commands:
      - echo Parsing Code coverage reports
reports:
  "my-reports-group":
  php-report:
    files:
      - "reports/php-unit.xml"
    file-format: "NUNITXML"
  nunit-report:
    files:
      - "reports/test-nunit.xml"
    file-format: "NUNITXML"
